### PR TITLE
Just a couple minor points to make packaging a little easier in Fedora.

### PR DESCRIPTION
**Pull request by audreytoskin**
Great work on this GNOME Shell extension! I'm trying to make this available as an RPM package in the default Fedora repositories.

I could work with the Makefile you already have. But writing an RPM package spec would be a little bit easier if you accepted these changes. Let me know what you think.

### CODE REVIEW

**Comment by audreytoskin** [comment]
...Preserving the file timestamps, I believe, is supposed to help with verifying that the the compiled package was actually built from the original sources listed in the package .spec file.

`DESTDIR` is just the installation path variable used in the the RPM `%make_install` macro. Though I also just see it more often in Makefiles in general.

**Comment by phocean** [comment]
Great! That's good news, and I am especially happy as I am a Fedora user myself.
No problem, I merged your changes in the dev branch.

I plan to make a new release in the next 2 weeks, if you are going to base your package on them.
Otherwise, I have no problem to push the changes to master before, if you prefer.

**Comment by audreytoskin** [comment]
Whenever is fine. I actually already have an [open package review request](https://bugzilla.redhat.com/show_bug.cgi?id=1394614) (if you want to follow along). I just thought I'd offer my small patches upstream when I was making sure the review request was for the latest version. The package spec still works in the meanwhile.

**Comment by olafhering** [comment]
DESTDIR is usually the offset to a target directory, not the target directory itself.

**Comment by audreytoskin** [comment]
Oops, @olafhering, you're right.

In the RPM macros, it looks like the usual setting is `DESTDIR=%{buildroot}`, which is treated as the *root filesystem* in a mock build chroot...

I guess I should just revert that commit.

**Pull request merged**
