### PR TITLE
Use ButtonBox for tray icons

### PR DESCRIPTION
**Pull request by nevesnunes**
See issue #25 for an explanation of these changes.

### CODE REVIEW

**Comment by phocean** [comment]
Very nice, merged with dev :-)
I will be testing. Thanks a lot.

**Comment by phocean** [comment]
Hmm no time to see it this week, but the tray disappears every time I suspend.

**Comment by phocean** [comment]
It could come from another extension, trying to reproduce and debug.
By the way, I tried with Adwaita and Arc and I am not sure if there is any change (maybe the outter spacing of the tray is a few pixel larger).
With which theme would it be more obvious?

**Comment by nevesnunes** [comment]
Suspend is working for me, try looking in journalctl for some error.

To test you can change the .panel-button selector in your theme's gnome-shell.css. For example, this will make padding significantly larger:

```
.panel-button {
    -natural-hpadding: 32px;
    -minimum-hpadding: 32px;
}
```

**Comment by phocean** [comment]
When it fails, I have such logs related to signal handling:

```
juil. 05 10:48:39 localhost gnome-session[2268]: Gjs-Message: JS LOG: Ignored exception from dbus method: Gio.IOErrorEnum: GDBus.Error:org.gnome.SessionManager.GeneralError: Unable to uninhibit: Invalid cookie
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: value "nan" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: value "nan" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: value "nan" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: value "nan" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: value "nan" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: value "nan" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: value "nan" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: value "nan" of type 'gfloat' is invalid or out of range for property 'width' of type 'gfloat'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620481'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620482'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620481'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620482'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620481'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620482'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620481'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620482'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620481'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620482'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620481'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620482'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620481'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620482'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620481'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620482'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620481'
juil. 05 10:48:40 localhost gnome-session[2268]: (gnome-shell:2433): GLib-GObject-WARNING **: gsignal.c:2569: instance '0x2f17460' has no handler with id '620482'
```

I don't understand how it happens (buggy app?) and how to debug it, it looks cryptic to me.

**Comment by nevesnunes** [comment]
The gfloat errors were related to improper icon size setting, I've pushed a fix but it seems unrelated to this problem.

That invalid cookie error is probably worth looking into. It's not much help, but you can monitor dbus method calls like this: 

```
dbus-monitor "interface='org.gnome.SessionManager'"
```

Then you can send like this (for example, to shutdown):

```
dbus-send --session --dest=org.gnome.SessionManager --type=method_call --print-reply --reply-timeout=2000 /org/gnome/SessionManager org.gnome.SessionManager.Shutdown
```

At least you can track down which method is causing the error, if there's any. Does this happen even with the extension disabled?

**Comment by phocean** [comment]
Thanks, I am testing all that.
It is not easy to reproduce, so it will take some time.

**Comment by phocean** [comment]
After a day of test, it does not seem to happen without the extension.
I have seen people on a forum complaining about stability, I am convinced it is for the same kind of error.

**Comment by phocean** [comment]
FYI, it is dropbox that makes the extension buggy sometimes. It also bugs with the legacy tray, but in a less visible manner.
My workaround for now is to execute Dropbox with systemctl, so without notification icon.
I will put a warning in the documentation, until I am able to make more tests about it.

**Comment by nevesnunes** [comment]
Thanks for letting me know. That Dropbox tray icon has a history of being quite buggy...

**Pull request merged**
