### PR TITLE
enabling compatibility for gnome shell 3.21.91

### PR DESCRIPTION
**Pull request by slowriot**

### CODE REVIEW

**Comment by phocean** [comment]
Thank you ;-)

**Comment by redianthus** [comment]
3.21.91 is just a temporary release, it shouldn't be added in the `metadata.json`.

And moreover, since [this commit](https://git.gnome.org/browse/gnome-shell/commit/?id=5e0e3e), released as a part of 3.21.92:

> Nowadays, the user interface has mostly stabilized with most changes happening under the hood. As a result, extensions written for previous versions of GNOME Shell are very much expected to keep working on updates, if it wasn't for the version check that requires a version bump in the extension metadata. There has been a setting to disable that check for a while, but it's existence isn't widely known (hence the common perception that "everything breaks on updates"). While there is still some risk that an out-of-date extension can be enabled without error, but fails spectacularly later (where we cannot catch the exception), it is reasonably small by now when compared to the ~95% of extensions that can be "unbroken", so swap the default value to disable version checks by default.

So, there's no need to update the `metadata.json` anymore. :)

**Comment by phocean** [comment]
Yes, it was what I replied in another issue here.
But I did accept this commit as it seems this version is used by many people (I don't know from what distro). Gnome 3.21 did not do the trick for some reason.
But you are correct, hopefully this will be the last update in this file!

**Comment by redianthus** [comment]
People from Debian Testing/Unstable or "rolling-release derivatives" I guess. But, 3.21.92 is already released and will replace it in a few days... It's already here in Debian Unstable.

**Comment by phocean** [comment]
Ho my god...
More issues to come! :p

**Comment by phocean** [comment]
I am going to update the setup instructions, by the way.

**Comment by redianthus** [comment]
No need to update the `metadata.json` with 3.21.92, so, no more issues. ;)

**Pull request merged**
